
package com.noranj.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.0
 * Fri May 04 22:12:55 PDT 2012
 * Generated source version: 2.6.0
 */

@XmlRootElement(name = "greetingResponse", namespace = "http://noranj.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "greetingResponse", namespace = "http://noranj.com/")

public class GreetingResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

