
package com.noranj.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.0
 * Fri May 04 22:12:56 PDT 2012
 * Generated source version: 2.6.0
 */

@XmlRootElement(name = "greeting", namespace = "http://noranj.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "greeting", namespace = "http://noranj.com/")

public class Greeting {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

