package org.noranj.formak.server;

import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.noranj.formak.server.domain.core.MailMessage;
import org.noranj.formak.server.domain.sa.SystemClientParty;
import org.noranj.formak.server.domain.sa.SystemUser;
import org.noranj.formak.server.service.JDOPMFactory;
import org.noranj.formak.server.service.SystemAdminServiceImpl;
import org.noranj.formak.server.service.servlet.SignUpMailHandlerServlet;
import org.noranj.formak.server.utils.Utils;
import org.noranj.formak.shared.Constants;
import org.noranj.formak.shared.dto.SystemClientPartyDTO;
import org.noranj.formak.shared.dto.SystemUserDTO;
import org.noranj.formak.shared.type.ActivityType;

import com.google.appengine.api.NamespaceManager;

/**
 * The methods in this class are used by services or servlets to implement services for System Admins.
 * 
 * This module, both source code and documentation, is in the Public Domain, and comes with NO WARRANTY.
 * See http://www.noranj.org for further information.
 *
 * @author
 * @since 0.3
 * @version 0.3
 * @change
 *
 */
public class SystemAdminHelper {

  protected static Logger logger = Logger.getLogger(SystemAdminHelper.class.getName());

	/**
	 * 
	 * @param mail
	 */
	public static String signupUser(MailMessage mail) {

		///XXX HERE 2012-MAR-27
		/**
		1- check emailAddress and if it is already a member, throw an exception or send an email or return message that the user is already a member.
		2- send email to notify sender about the status of their email.
		3- add organization (client) to the body of email in case someone knows their client name. use the name to find the client and add the current user to that client.
		3-1- another way could be using the domain of email address to search for the client.
		*/
		
		Map<String, String> dataFieldsFromBody = Utils.buildMap(mail.getBody().getContentAsString());
		
		if (logger.isLoggable(Level.FINE)) {
			logger.fine("Attributes in body are {");
			for(String key:dataFieldsFromBody.keySet()) {
				logger.fine("key=["+key+"] value=["+dataFieldsFromBody.get(key)+"]");
			} // for
			logger.fine("} Attributes in body");
		}
		
    SystemClientPartyDTO sysClientDTO = new SystemClientPartyDTO(dataFieldsFromBody);
    
    sysClientDTO.setActivityType(ActivityType.Active); // to make sure the user is active and can login.
    if (sysClientDTO.getName()==null) {
    	sysClientDTO.setName("client-guest-" + System.currentTimeMillis());
    }
    
    SystemUserDTO sysUserDTO = new SystemUserDTO(dataFieldsFromBody);
    
    sysUserDTO.setActivityType(ActivityType.Active); // to make sure the user is active and can login.
    sysUserDTO.setEmailAddress(mail.getFrom().getAddress()); // to overwrite the emailAddress in the mail body
    
    //Extract First Name and Last Name from emailAddresFROM
    if (sysUserDTO.getFirstName()==null && sysUserDTO.getLastName()==null) {
    	sysUserDTO.setNames(mail.getFrom().getPersonal()); // extract the first name and last name from the email
    	//still no value
    	if (sysUserDTO.getFirstName()==null && sysUserDTO.getLastName()==null) {
    		sysUserDTO.setFirstName("Guest"); //TODO review 
    		sysUserDTO.setLastName(String.valueOf(System.currentTimeMillis()));
    	}
    }
		
    if (logger.isLoggable(Level.FINE)) {
			logger.fine("User DTO is ["+sysUserDTO.toString()+"]");
    }
    sysUserDTO.setId(signup(sysClientDTO, sysUserDTO));
    logger.info("A new user successfully signed up. userid["+sysUserDTO.getId()+"] email["+sysUserDTO.getEmailAddress()+"]");
    
		return(sysUserDTO.getId());
		
	}
	
	
  //TODO I am not sure about the parameters. BA-2012-03-22
  /**
   * it can be signed up by email and UI.
   * @return userID generated by the system for the new user.
   * @since 0.3.20120322
   * @version @since 0.3.20120322
   */
  public static String signup(SystemClientPartyDTO systemClientPartyDTO, SystemUserDTO systemUserDTO) {

    String currentNameSpace = NamespaceManager.get();
    NamespaceManager.set(Constants.C_SYSTEM_ADMIN_NAMESPACE); 

    try {
    	
	  	DALHelper<SystemClientParty> systemClientHelper = new DALHelper<SystemClientParty>(JDOPMFactory.getTxOptional(), SystemClientParty.class);

	  	SystemClientParty newSystemClientParty;
	    
	  	// check if client exist
	  	if(systemClientPartyDTO.getId()!=null) {
	  		newSystemClientParty =systemClientHelper.getEntityById(systemClientPartyDTO.getId(), null, 1); 
	  		if (newSystemClientParty == null) {
	  			logger.severe("SystemClientparty["+systemClientPartyDTO.getId()+"] does not exist in the system.");
	  			return null; //FIXME here
	  		}
	  	}
	  	else { // add client if it doesn't exist
	  		newSystemClientParty = new SystemClientParty(systemClientPartyDTO);
	  		systemClientHelper.storeEntity(newSystemClientParty);
	  	}
	  	
	  	//link the user to its parent.
	  	systemUserDTO.setParentClientId(newSystemClientParty.getId());
	  	
	  	// save the user in the system
	    DAL1ToNHelper<SystemClientParty, SystemUser> systemClientHelper2 = new DAL1ToNHelper<SystemClientParty, SystemUser>(JDOPMFactory.getTxOptional(), SystemClientParty.class, SystemUser.class);
	    SystemUser sysUser = new SystemUser(systemUserDTO);
	    systemUserDTO.setId(systemClientHelper2.addChildEntity(sysUser));
	    return(systemUserDTO.getId());
	    
    } finally {
    	NamespaceManager.set(currentNameSpace);
    }
  }

		
} //class
